# Generated by Django 5.2.7 on 2025-10-22 13:33

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Nom complet')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Genre')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/%Y/%m/', verbose_name='Photo de profil')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name="Numéro de pièce d'identité")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Numéro de téléphone principal')),
                ('phone_secondary', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numéro de téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse personnelle')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('role', models.CharField(choices=[('client', 'Client'), ('chauffeur', 'Chauffeur'), ('caissier', 'Caissier'), ('livreur', 'Livreur'), ('agency_manager', "Chef d'Agence"), ('central_manager', "Chef d'Agence Centrale"), ('national_manager', "Chef d'Agence Nationale"), ('dg', 'Directeur Général'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name='Rôle')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='Matricule employé')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('pending', 'En attente')], default='active', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte activé')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès administration')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superutilisateur')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('activation_token', models.CharField(blank=True, max_length=100, null=True, verbose_name="Token d'activation")),
                ('activation_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de connexions')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='locations.agency', verbose_name='Agence')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
