# Generated by Django 5.2.7 on 2025-10-22 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='QR Token')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('ticket_code', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Code du ticket')),
                ('passenger_name', models.CharField(max_length=255, verbose_name='Nom du passager')),
                ('passenger_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du passager')),
                ('passenger_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du passager')),
                ('passenger_id', models.CharField(blank=True, max_length=50, verbose_name="Pièce d'identité")),
                ('seat_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de siège')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('boarded', 'Embarqué'), ('missed', 'Non embarqué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='confirmed', max_length=20, verbose_name='Statut')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Scanné à')),
                ('boarding_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'embarquement")),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['seat_number', 'passenger_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], max_length=20, verbose_name='Méthode de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('provider_ref', models.CharField(blank=True, max_length=100, verbose_name='Référence prestataire')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé à')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='locations.agency', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Code de réservation')),
                ('travel_date', models.DateField(verbose_name='Date de voyage')),
                ('total_seats', models.PositiveIntegerField(default=1, verbose_name='Nombre de places')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='pending', max_length=20, verbose_name='Statut')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire à')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created'],
            },
        ),
    ]
