# Generated by Django 5.2.7 on 2025-10-22 13:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='QR Token')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('tracking_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code de suivi')),
                ('sender_name', models.CharField(max_length=120, verbose_name="Nom de l'expéditeur")),
                ('sender_phone', models.CharField(max_length=30, verbose_name='Téléphone expéditeur')),
                ('sender_address', models.TextField(blank=True, verbose_name='Adresse expéditeur')),
                ('receiver_name', models.CharField(max_length=120, verbose_name='Nom du destinataire')),
                ('receiver_phone', models.CharField(max_length=30, verbose_name='Téléphone du destinataire')),
                ('receiver_address', models.TextField(verbose_name='Adresse de livraison')),
                ('category', models.CharField(choices=[('small', 'Petit colis (< 5kg)'), ('medium', 'Colis moyen (5-20kg)'), ('large', 'Gros colis (> 20kg)'), ('document', 'Document'), ('fragile', 'Fragile'), ('other', 'Autre')], default='medium', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description du contenu')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensions (L x l x H)')),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valeur déclarée')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base')),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'assurance")),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('status', models.CharField(choices=[('created', 'Enregistré'), ('loaded', 'Chargé pour transport'), ('at_agency', "Arrivé à l'agence"), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('returned', 'Retourné'), ('lost', 'Perdu')], default='created', max_length=20, verbose_name='Statut')),
                ('requires_signature', models.BooleanField(default=True, verbose_name='Signature requise')),
                ('requires_delivery_confirmation', models.BooleanField(default=True, verbose_name='Confirmation de livraison')),
                ('home_delivery', models.BooleanField(default=False, verbose_name='Livraison à domicile')),
                ('insurance_required', models.BooleanField(default=False, verbose_name='Assurance souscrite')),
                ('delivery_proof', models.ImageField(blank=True, null=True, upload_to='parcels/delivery_proofs/', verbose_name='Preuve de livraison')),
                ('recipient_signature', models.ImageField(blank=True, null=True, upload_to='parcels/signatures/', verbose_name='Signature du destinataire')),
                ('delivery_code', models.CharField(blank=True, max_length=10, verbose_name='Code de livraison')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Livraison estimée')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Livraison effective')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives de livraison')),
                ('current_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels_current', to='locations.agency', verbose_name='Agence actuelle')),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_current', to='locations.city', verbose_name='Ville actuelle')),
                ('current_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='transport.trip', verbose_name='Voyage actuel')),
                ('destination_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_destination', to='locations.agency', verbose_name='Agence de destination')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_destination_city_final', to='locations.city', verbose_name='Ville de destination finale')),
                ('last_handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Dernier gestionnaire')),
                ('origin_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_origin', to='locations.agency', verbose_name="Agence d'origine")),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_origin_city', to='locations.city', verbose_name="Ville d'origine")),
                ('receiver_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_destination_city', to='locations.city', verbose_name='Ville de destination')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('created', 'Colis enregistré'), ('loaded', 'Chargé pour transport'), ('at_agency', "Arrivé à l'agence"), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('returned', 'Retourné'), ('lost', 'Perdu'), ('exception', 'Incident / Anomalie'), ('delivery_attempt', 'Tentative de livraison'), ('hold', 'Mis en attente'), ('customs', 'Passage en douane')], max_length=20, verbose_name='Événement')),
                ('status', models.CharField(choices=[('created', 'Enregistré'), ('loaded', 'Chargé pour transport'), ('at_agency', "Arrivé à l'agence"), ('out_for_delivery', 'En livraison'), ('delivered', 'Livré'), ('returned', 'Retourné'), ('lost', 'Perdu')], max_length=20, verbose_name='Statut')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Photos')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_events', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_events', to='locations.agency', verbose_name='Agence')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='Ville')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='parcel.parcel', verbose_name='Colis')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_events', to='transport.trip', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Événement de suivi',
                'verbose_name_plural': 'Événements de suivi',
                'ordering': ['-ts'],
            },
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['tracking_code'], name='parcel_parc_trackin_6f4e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['receiver_phone'], name='parcel_parc_receive_a3745b_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='parcel_parc_status_50161c_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['current_agency'], name='parcel_parc_current_45735d_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['origin_agency'], name='parcel_parc_origin__a9b20e_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['destination_agency'], name='parcel_parc_destina_194af5_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['parcel', 'ts'], name='parcel_trac_parcel__86eec5_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event'], name='parcel_trac_event_df3f31_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['agency'], name='parcel_trac_agency__f3fe8c_idx'),
        ),
    ]
