# Generated by Django 5.2.7 on 2025-10-22 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Nom légal')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo principal')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo clair')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo sombre')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Favicon')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(max_length=254, verbose_name='Email principal')),
                ('email_support', models.EmailField(blank=True, max_length=254, verbose_name='Email support')),
                ('email_sales', models.EmailField(blank=True, max_length=254, verbose_name='Email commercial')),
                ('address', models.TextField(verbose_name='Adresse principale')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('rc_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='Numéro NIF')),
                ('nis', models.CharField(blank=True, max_length=50, verbose_name='Numéro NIS')),
                ('ai_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro AI')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('timezone', models.CharField(default='Africa/Douala', max_length=50, verbose_name='Fuseau horaire')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue par défaut')),
                ('max_seats_per_booking', models.PositiveIntegerField(default=10, verbose_name='Nombre maximum de sièges par réservation')),
                ('booking_expiry_minutes', models.PositiveIntegerField(default=30, verbose_name="Délai d'expiration des réservations (minutes)")),
                ('allow_online_payment', models.BooleanField(default=True, verbose_name='Paiement en ligne activé')),
                ('max_parcel_weight', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Poids maximum des colis (kg)')),
                ('parcel_insurance_required', models.BooleanField(default=False, verbose_name='Assurance colis obligatoire')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('enable_sms_notifications', models.BooleanField(default=True, verbose_name='Notifications SMS activées')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='Notifications email activées')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('keywords', models.TextField(blank=True, verbose_name='Mots-clés')),
            ],
            options={
                'verbose_name': 'Configuration entreprise',
                'verbose_name_plural': 'Configurations entreprise',
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('category', models.CharField(choices=[('general', 'Général'), ('reservation', 'Réservation'), ('payment', 'Paiement'), ('parcel', 'Colis'), ('notification', 'Notification'), ('security', 'Sécurité')], default='general', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Entier'), ('float', 'Décimal'), ('boolean', 'Booléen'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Type de données')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['category', 'key'],
            },
        ),
    ]
