# Generated by Django 5.2.7 on 2025-10-22 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(help_text='Code ISO-3166 alpha-2/3', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.country')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name="Nom de l'agence")),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code agence')),
                ('level', models.CharField(choices=[('national', 'Siège national'), ('central', 'Agence centrale (ville)'), ('local', 'Agence de quartier')], default='local', max_length=20)),
                ('type', models.CharField(choices=[('departure', 'Agence de départ'), ('arrival', "Agence d'arrivée"), ('cargo', 'Agence de colis'), ('sales', 'Point de vente / Caisse'), ('service', 'Service administratif'), ('other', 'Autre')], default='sales', max_length=20)),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, verbose_name='Agence active')),
                ('parent_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_agencies', to='locations.agency')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='locations.city')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['city__name', 'name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='locations_a_city_id_bb13ae_idx'), models.Index(fields=['code'], name='locations_a_code_fbdf57_idx'), models.Index(fields=['level'], name='locations_a_level_0d4994_idx'), models.Index(fields=['type'], name='locations_a_type_918843_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'name'], name='locations_c_country_a5360f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
    ]
