# Generated by Django 5.2.7 on 2025-10-22 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de la route')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distance (km)')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='locations.agency', verbose_name='Agence')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_destination', to='locations.city', verbose_name="Ville d'arrivée")),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_origin', to='locations.city', verbose_name='Ville de départ')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(verbose_name='Ordre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée (minutes)')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_destination', to='locations.city', verbose_name='Arrivée')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_origin', to='locations.city', verbose_name='Départ')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='transport.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Tronçon',
                'verbose_name_plural': 'Tronçons',
                'ordering': ['order'],
                'unique_together': {('route', 'origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(verbose_name='Heure de départ')),
                ('days_of_week', models.CharField(help_text="Ex: 'lun,mar,mer' ou 'quotidien'", max_length=50, verbose_name='Jours de circulation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='locations.agency', verbose_name='Agence')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='transport.leg', verbose_name='Tronçon')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('departure_dt', models.DateTimeField(verbose_name='Date et heure de départ')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('boarding', 'Embarquement'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='boarding', max_length=20, verbose_name='Statut')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.agency', verbose_name='Agence')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.schedule', verbose_name='Horaire')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('departure', 'Départ'), ('stop', 'Arrêt'), ('passenger_descent', 'Descente passager'), ('passenger_boarding', 'Embarquement passager'), ('incident', 'Incident'), ('accident', 'Accident'), ('arrival', 'Arrivée finale')], max_length=30, verbose_name="Type d'événement")),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='Ville')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transport.trip', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Événement voyage',
                'verbose_name_plural': 'Événements voyage',
            },
        ),
        migrations.CreateModel(
            name='TripPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('passenger_name', models.CharField(max_length=255, verbose_name='Nom du passager')),
                ('seat_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de siège')),
                ('boarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Embarqué à')),
                ('disembarked_at', models.DateTimeField(blank=True, null=True, verbose_name='Débarqué à')),
                ('is_onboard', models.BooleanField(default=True, verbose_name='À bord')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_passengers', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('disembarked_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='Ville de débarquement')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip_passenger', to='reservations.ticket', verbose_name='Ticket')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='transport.trip', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Passager voyage',
                'verbose_name_plural': 'Passagers voyage',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'immatriculation")),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('type', models.CharField(default='bus', max_length=30, verbose_name='Type de véhicule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='locations.agency', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='Véhicule'),
        ),
    ]
